<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
 <HEAD>
  <TITLE> New Document </TITLE>
  <META NAME="Generator" CONTENT="EditPlus">
  <META NAME="Author" CONTENT="">
  <META NAME="Keywords" CONTENT="">
  <META NAME="Description" CONTENT="">
 </HEAD>

 <BODY>
  <CENTER>
  <H1>CREDIT ENTRY FORM</H1>
  <BR>
  <FORM METHOD="POST" ACTION="insertcrd.php">
  <TABLE>
  <TR>
	<TD>SESSION:</TD>
	<TD><INPUT TYPE="TEXT" NAME="SESSION"/></TD>
</TR>

<TR>
<TD>SEMESTER CODE:</TD>
<TD><INPUT TYPE="TEXT" NAME="SEM_CODE"/></TD>
</TR>

<TR>
<TD>SUBJECT ORDER</TD>
<TD><INPUT TYPE="TEXT" NAME="SUBJE_ORDE"/></TD>
</TR>

<TR>
<TD>SUBJECT CODE</TD>
<TD><INPUT TYPE="TEXT" NAME="SUBJE_CODE"/></TD>
</TR>

<TR>
<TD>S_R_P</TD>
<TD><INPUT TYPE="TEXT" NAME="S_R_P"/></TD>
</TR>

<TR>
<TD>G_E</TD>
<TD><INPUT TYPE="TEXT" NAME="G_E"/></TD>
</TR>

<TR>
<TD>E NO.</TD>
<TD><INPUT TYPE="TEXT" NAME="ENO"/></TD>
</TR>

<TR>
<TD>FLAG</TD>
<TD><INPUT TYPE="TEXT" NAME="FLAG"/></TD>
</TR>

<TR>
<TD>VALUE</TD>
<TD><INPUT TYPE="TEXT" NAME="VALUE"/></TD>
</TR>

<TR>
<TD>LECTURE</TD>
<TD><INPUT TYPE="TEXT" NAME="LECTURE"/></TD>
</TR>

<TR>
<TD>THEORY</TD>
<TD><INPUT TYPE="TEXT" NAME="THEORY"/></TD>
</TR>

<TR>
<TD>PRACTICAL</TD>
<TD><INPUT TYPE="TEXT" NAME="PRACTICAL"/></TD>
</TR>

<TR>
<TD>WEIGHTAGE</TD>
<TD><INPUT TYPE="TEXT" NAME="WEIGHTAGE"/></TD>
</TR>

<TR>
<TD>OBSOLETE</TD>
<TD><INPUT TYPE="TEXT" NAME="OBSOLETE"/></TD>
</TR>

</TABLE>
<BR>
<INPUT TYPE="SUBMIT" VALUE="SUBMIT"/>
</FORM>
 </BODY>
</HTML>
