<?php
include "ssconnection.php";
$sql="UPDATE `esub_mst` SET `SESSION`= '$_POST[SESSION]',`SEM_CODE`= '$_POST[SEM_CODE]',`SUBJE_CODE`='$_POST[SUBJE_CODE]',`SUBJE_NAME`='$_POST[SUBJE_NAME]',`TEACHER1`='$_POST[TEACHER1]',`DEPT1`='$_POST[DEPT1]',`PSETTER1`='$_POST[PSETTER1]',`PEVALUATOR1`='$_POST[PEVALUATOR1]',`MSUBMISSION1`='$_POST[MSUBMISSION1]',`TEACHER2`='$_POST[TEACHER1]',`DEPT2`='$_POST[DEPT2]',`PSETTER2`='$_POST[PSETTER2]',`PEVALUATOR2`='$_POST[PEVALUATOR2]',`MSUBMISSION2`='$_POST[MSUBMISSION2]',`TEACHER3`='$_POST[TEACHER3]',`DEPT3`='$_POST[DEPT3]',`PSETTER3`='$_POST[PSETTER3]',`PEVALUATOR3`='$_POST[PEVALUATOR3]',`MSUBMISSION3`='$_POST[MSUBMISSION3]',`TEACHER4`='$_POST[TEACHER4]',`DEPT4`='$_POST[DEPT4]',`PSETTER4`='$_POST[PSETTER4]',`PEVALUATOR4`='$_POST[PEVALUATOR4]',`MSUBMISSION4`='$_POST[MSUBMISSION4]',`TEACHER5`='$_POST[TEACHER5]',`DEPT5`='$_POST[DEPT5]',`PSETTER5`='$_POST[PSETTER5]',`PEVALUATOR5`='$_POST[PEVALUATOR5]',`MSUBMISSION5`='$_POST[MSUBMISSION5]',WHERE `ID`='$_POST[eid];";

mysql_query($sql);
header("location:tablesub.php");
?>